name: arobatv
description: The aroba tv app.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.1
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  email_validator: '^2.1.16'
  dio : 
  video_player:
  flutter_pw_validator: ^1.2.1
  connectivity_plus: ^2.3.7
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  flutter_svg: ^1.1.5
  pin_code_fields: ^7.3.0
  sms_autofill: ^2.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/robotorobotoromanregular400.ttf
          weight: 400
        - asset: assets/fonts/robotomedium500.ttf
          weight: 500
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/urbanisturbanistromanbold700.ttf
          weight: 700
        - asset: assets/fonts/urbanisturbanistromansemibold600.ttf
          weight: 600
        - asset: assets/fonts/urbanisturbanistromanmedium500.ttf
          weight: 500
    - family: Poppins
      fonts: 
        - asset: assets/fonts/poppinssemibold600.ttf
          weight: 600
        - asset: assets/fonts/poppinsbold700.ttf
          weight: 700
        - asset: assets/fonts/poppinsregular400.ttf
          weight: 400
